
project_id = "ncpnlnucffgoscufyyyx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = true

[auth]
enabled = true
port = 54326
site_url = "https://9407bbda-2b57-4bd7-838a-73839fb60e6a.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = true
enable_email_change_confirmations = true
enable_phone_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
template = {}

[auth.sms]
enable_signup = false
enable_confirmations = false
template = {}

[functions.send-confirmation-email]
verify_jwt = false

[analytics]
enabled = false
