
-- Insertar algunos eventos de ejemplo para testing
INSERT INTO events (
  restaurant_id,
  name,
  description,
  event_date,
  start_time,
  end_time,
  entry_price,
  is_free,
  category,
  requires_reservation,
  available_seats,
  contact_for_reservations,
  age_restriction,
  dress_code,
  tags,
  is_active
) VALUES 
(
  2, -- Asumiendo que el restaurant_id es 2 basado en los logs
  'Noche de Jazz en Vivo',
  'Disfruta de una velada única con música jazz en directo mientras cenas.',
  '2025-08-15',
  '20:30:00',
  '23:00:00',
  15.00,
  false,
  'Música',
  true,
  40,
  'Reservas: 123-456-789',
  'over_18',
  'smart_casual',
  '["jazz", "música en vivo", "cena"]',
  true
),
(
  2,
  'Cata de Vinos Maridaje',
  'Cata de vinos españoles con maridaje de tapas gourmet.',
  '2025-08-20',
  '19:00:00',
  '21:30:00',
  25.00,
  false,
  'Gastronomía',
  true,
  20,
  'info@restaurante.com',
  'over_21',
  'casual',
  '["vino", "maridaje", "tapas"]',
  true
),
(
  2,
  'Taller de Cocina Familiar',
  'Aprende a cocinar platos tradicionales en familia. Actividad gratuita.',
  '2025-08-25',
  '11:00:00',
  '14:00:00',
  null,
  true,
  'Educativo',
  true,
  15,
  'talleres@restaurante.com',
  'all_ages',
  'casual',
  '["cocina", "familiar", "educativo"]',
  true
);
